### ISSUE TITLE
Command line is too long

### ISSUE THREAD

**Issue by ingro** [vladikoff/grunt-devtools#15] opened 2013-09-17 08:00 UTC
Hello, I've successfully installed globally grunt-devtools and its chrome extension, and it's running fine on one of my old grunt project.

Anyway in the one I'm currently working to, when I type `grunt-devtools` it returns an error, I'm not sure what the exact translation is but should be something like "Command line is too long".

The tasks are running fine from the command line so I'm not sure what's going wrong...

**Comment by vladikoff** [comment] 2013-09-17 14:56
@ingro oh haven't seen that error. I will investigate, thanks for reporting this !

**Comment by vladikoff** [comment] 2013-09-17 14:57
@ingro are you on Windows by any chance?

**Comment by ingro** [comment] 2013-09-17 15:08
Yes, Windows 7 x64.

**Comment by ingro** [comment] 2013-09-17 15:30
I know that isn't much, but that's all the command line is returning to me. If I can help you to better hunt down the problem in some other way let me know!

**Comment by vladikoff** [comment] 2013-09-17 15:32
@ingro Hey thanks for the quick response. I know what the problem is, I will patch it up. It only happens in Windows due to certain command line limitations.

**Comment by vladikoff** [comment] 2013-09-17 18:12
@ingro, a temporary solution might be to run `grunt-devtools` in PowerShell, could you try that?

**Comment by ingro** [comment] 2013-09-17 18:26
Actually I'm not at work anymore, but I already tried that if I remember with no luck :(

**Comment by vladikoff** [comment] 2013-09-17 23:30
Ok I was able to reproduce this issue, I've created a branch with a fix at https://github.com/vladikoff/grunt-devtools/tree/windows-cli-fix 
I will release this tomorrow or after tomorrow. Will close this ticket when the fix is live. 
Thanks!

**Comment by ingro** [comment] 2013-09-18 00:09
Thanks to you for your fast answer, keep up the good work! :D

**Comment by vladikoff** [comment] 2013-09-28 04:24
Just pushed 0.2.1 that fixes this issue.

**Closed as completed by vladikoff** 2013-09-28 04:24 UTC
